<?xml version="1.0" encoding="UTF-8"?>

<!-- Dont Forget to make id unique using DTD schema -->
<!DOCTYPE root[
        <!ELEMENT root (question+)>
        <!ELEMENT question (#PCDATA)>
        <!ATTLIST question id ID #REQUIRED>
        ]>
<root>
    <question id="q4">What is DTD ?</question>
    <question id="q1"> What is DOM ?</question>
    <question id="q2"> What are Leaves ?</question>
    <question id="q5">What is DTD ?</question>

</root>